# general configs
verbose:
  desc: prints intermediate results to sdt.out
  value: true
data_dir:
  desc: validation data dir
  value: /g/kreshuk/hilt/projects/data/artificial_cells/val
agent_model_name:
  desc: if not empty, agent will be initialized with the state dict at this location
  value: '' # agent_model_svpfe.pth

# embedding network config
fe_model_name:
  desc: path to state dict of trained model
  value: /g/kreshuk/hilt/storage/synthetic_noisy_nuclei/fe_l2_cosine_usaff.pth
dim_embeddings:
  desc: number of embedding feature channels
  value: 16
backbone:
  desc: config for the embedding network
  value:
    name: UNet2D
    in_channels: 3
    out_channels: 16
    # use Groupnorm instead of Batchnorm for DSB; Batchnorm introduces artifacts around nuclei due to the difference
    # in intensity distribution between images with large and small cells
    layer_order: bcr
  #  num_groups: 8
    f_maps: [32, 64, 128]
    #conv_padding: 0
    final_sigmoid: false
    is_segmentation: false

gnn_n_hidden:
  desc: number of hidden layers in graph conv blocks
  value: 4
gnn_hl_factor:
  desc: factor by which feature size of hidden featuremaps in gnn increases/decreases
  value: 32

patch_manager:
  desc: if training should happen on patches, this is the config for the patch manager
  value:
    name: none # rotated, no_cross, none
    reorder_sp: true


# specific configs for the sac algorithm
reward_function:
  desc: one of sub_graph_dice, artificial_cells, artificial_cells_EllipticFit
  value: sub_graph_dice
gt_edge_overlap_thresh:
  desc: if using gt edges this is the overlap thresh of the underlying gt for a gt edge to be 1
  value: 0.5
std_bounds:
  desc: norm bounds of predicted std dev
  value: [0.01, 5.0]
mu_bounds:
  desc: norm bounds of predicted mean
  value: [-5, 5]

#policy_warmup:
#  desc: the policy might need pretraining to make training faster
#    value:
#    lr: 1e-3
#
#    n_iterations: 500 # number of iterations of feature extrqactor warmup
#    batch_size: 1  # batch size for feature extractor warmup
#
#    patch_manager:
#      name: no_cross # rotated, no_cross, none
#      patch_shape: [512, 512]
#      patch_stride: [128, 128]
#      reorder_sp: true

