name: RLForSeg_env
channels:
  - pytorch
  - cpape
  - conda-forge
  - defaults
  - paulhilt
dependencies:
  - elf
  - pytorch=1.9
  - cudatoolkit=10.2
  - matplotlib
  - opencv
  - rag_utils
  - affogato
  - wandb
  - pip
  - pip:
    - -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
    - torch-scatter