# @package _group_
# feature extractor
model_name: 'embedding_net'
load_pretrained: false
optim: "none"  # none/rl_loss  # optimize feature extractor with ril loss, fe extractor optimization works only when fe is part of the agent (MC). In the embedding space environment fe is part of the env

update_frequency: 10 # optim step every n-th step
n_prep_steps: 100  # num steps before optimization begins
n_embedding_features: 16  # number of embedding feature channels
n_raw_channels: 3  # number of channels in current state
contrastive_delta_dist: 0.3
contrastive_delta_var: 0.1
max_pixel_in_dist_mat: 8191

warmup:  # the feature extractor might need pretraining to produce meaningful features
  # Adam optim conf
  lr: 1e-4
  betas: [0.9, 0.999]

  method: 'affinity_contrast'
  n_iterations: 2000 # number of iterations of feature extrqactor warmup
  batch_size: 10  # batch size for feature extractor warmup

  patch_shape: [256, 256]
  patch_stride: [16, 16]
  reorder_sp: true
  patch_manager: no_cross # rotated, no_cross, none


